apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
  - tests/
commands:
  - command: kubectl apply -f ./deploy/crds.yml
  - command: kubectl apply -f ./tests/namespace-watch-rbac.yaml
timeout: 120
